Cfl 15
MorozovaAN/cards-for-learn pull request #23
Opened 2023-02-06 14:24 UTC by Oldeg

2023-02-06 14:40 UTC, lily1215z approved these changes

2023-02-06 15:14 UTC, MorozovaAN requested changes

2023-02-06 15:14 UTC, MorozovaAN commented on package.json
> +    "@mui/icons-material": "^5.11.0",
иконки получается не нужны

2023-02-06 15:14 UTC, MorozovaAN commented on src/UI/input/Input.tsx
> +          type={'submit'}
скобки эти { } не нужны

2023-02-06 15:14 UTC, MorozovaAN commented on src/UI/nav-link/NavLink.module.scss
> +@import '../../style-mixins/fonts-mixins';
тут импорт идет так: @import 'src/style-mixins/fonts-mixins';

2023-02-06 15:14 UTC, MorozovaAN commented on src/components/auth/UpdateProfileAvatar.module.scss
> +    background-color: #808080;
все цвета нужно взять из переменных, вместо этого подойдет возможно 
--color-on-primary-light-400 или --color-on-primary-light-500

2023-02-06 15:14 UTC, MorozovaAN commented on src/components/auth/UpdateProfileAvatar.module.scss
> +    border: 1px solid #FFFFFF;
это цвет --color-background-base

2023-02-06 15:14 UTC, MorozovaAN commented on src/components/auth/UpdateProfileName.tsx
> +  //нужно чтоб в инпуте сохранялось имя прошлое при обновлении
может комменты тоже на англ писать будем, раз уж у нас весь проект на англ

2023-02-06 15:14 UTC, MorozovaAN commented on src/components/auth/UpdateProfileName.tsx
> +  const profileName = useTypedSelector(nameSelector)
нейминг: const userName ...

2023-02-06 15:14 UTC, MorozovaAN commented on src/modules/auth/profile/Profile.module.scss
> +.profile_img img {
селекторы используем только в крайнем случае, если без него ну ника. Тут можно обойтись, имя класса img дать изображению, получится .img { ... }

2023-02-06 15:14 UTC, MorozovaAN commented on src/modules/auth/profile/Profile.module.scss
> +.profile_btn_logout {
название класса: logout или btnLogout если там какие то еще кнопки есть и можно спутать, если нет то просто logout 

стили кнопке нужны по-минимуму, потому что все основные стили  есть в коммон кнопке, удали все стили в своем классе (кроме after элемента) и выбери вариант кнопки styleType='primary', посмотри как там будет, скорее всего понадобится только width: 127px; и что-то для иконки логаута, но может только ширина и все

кнопка будет зеленой - это ок, потому что белая без тени будет не видна, а теней теперь у нас нет в дизайне

2023-02-06 15:14 UTC, MorozovaAN commented on src/modules/auth/profile/Profile.module.scss
> +    content: url('../../../assets/img/icons/profile_logout.png');
иконка логаута останется черной, а текст кнопки будет белым после того как ты её поменяешь, на это забей, я её перекрашу в фигме и в свг скачаю потом вставлю и все будет норм

2023-02-06 15:14 UTC, MorozovaAN commented on src/modules/auth/profile/Profile.module.scss
> +.profile_name_edit {
это кнопка styleType='icon' 

cursor: pointer - не нужно, потому что курсо поинтер есть в самой кнопке
а марджин добавь элементу имени и этот класс можно удалить

2023-02-06 15:14 UTC, MorozovaAN commented on src/modules/auth/profile/Profile.module.scss
> +.profile_name {
название класса - name

2023-02-06 15:14 UTC, MorozovaAN commented on src/modules/auth/profile/Profile.tsx
> +    <>
пустой тег не нужен

2023-02-06 15:14 UTC, MorozovaAN commented on src/modules/auth/profile/Profile.tsx
> +              <img src={editName} alt={'edit name'} />
alt='edit name icon'

2023-02-06 15:14 UTC, MorozovaAN commented on src/modules/auth/profile/Profile.tsx
> +        <span className={s.email}>
тег < p > тут больше подойдет, проверь что в стилях ему не добавятся марджины сверху и снизу (по сути не должны, потому что я их обнуляю в миксинах, но вдруг)

2023-02-06 15:14 UTC, MorozovaAN commented on src/modules/auth/profile/Profile.tsx
> +            <span onClick={editModeOpen} className={s.profile_name_edit}>
поменять на common кнопку c пропсом styleType='icon'

2023-02-06 15:14 UTC, MorozovaAN commented on src/modules/auth/profile/Profile.tsx
> +        <Button styleType={'secondary'} className={s.profile_btn_logout} onClick={logout}>
styleType='primary', она будет зеленой - это ок

2023-02-06 15:14 UTC, MorozovaAN commented on src/pages/profile-page/ProfilePage.module.scss
> +@include navigateLink()
тут чета не то, стили должны быть в самом реюз компоненте NavLink, нужно ему указать styleType='primary'

2023-02-06 15:14 UTC, MorozovaAN commented on src/pages/profile-page/ProfilePage.tsx
> +      <NavLink url={PATH.PACKS} className={s.link}>
styleType='primary' а класс удали (и отсюда и из стилей)

2023-02-07 08:47 UTC, MorozovaAN approved these changes

2023-02-07 08:48 UTC, merged